using BBStats.Data.Entites;
using Microsoft.EntityFrameworkCore;

namespace BBStats.Data;

public class AppDbContext : DbContext
{
	public AppDbContext(DbContextOptions<AppDbContext> options)
		   : base(options)
	{
	}
	public DbSet<Character> Characters => Set<Character>();
	public DbSet<PlayerGame> PlayersGames => Set<PlayerGame>();
	public DbSet<Game> Games => Set<Game>();
	public DbSet<Matchup> Matchups => Set<Matchup>();
	public DbSet<Player> Players => Set<Player>();
	public DbSet<PlayerCharacterStat> PlayersCharactersStats => Set<PlayerCharacterStat>();
    //  We need to maintain a list of ignored players to prevent them from being added back to the database after deleting them and to prevent them from being added to the database when adding new games
	public DbSet<IgnoredPlayer> IgnoredPlayers => Set<IgnoredPlayer>();

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);

		modelBuilder.Entity<IgnoredPlayer>(entity =>
		{
			entity.HasKey(x => x.PlayerId);
			// To ensure the PlayerId is not treated as an entity key that is generated by the database, we need to configure it to be a regular property
    		entity.Property(x => x.PlayerId)
          		.ValueGeneratedNever();

			entity.Property(x => x.Reason)
				.HasMaxLength(250);

			entity.Property(x => x.CreatedAt)
				.HasDefaultValueSql("GETUTCDATE()");
		});

		modelBuilder.Entity<Character>().HasData(CharactersSeed.All);

		modelBuilder.Entity<Player>(entity =>
		{
			entity.Property(p => p.Id).ValueGeneratedNever();
			// automatically exclude ignored players from all public queries
			entity.HasQueryFilter(p =>
				!IgnoredPlayers.Any(ip => ip.PlayerId == p.Id));
		});

		modelBuilder.Entity<PlayerCharacterStat>(entity =>
		{
			entity.HasKey(u => new { u.PlayerId, u.CharacterId });
			entity.Property(u => u.MaxRating).HasDefaultValue(1000);

			entity.HasOne(u => u.Player)
				  .WithMany(p => p.CharactersStat)
				  .HasForeignKey(u => u.PlayerId)
				  .OnDelete(DeleteBehavior.Cascade);

			entity.HasOne(u => u.Character)
				  .WithMany() 
				  .HasForeignKey(u => u.CharacterId)
				  .OnDelete(DeleteBehavior.Cascade);

			//entity.HasMany(ps => ps.Games)
			//	  .WithOne(pg => pg.CharacterStat)  
			//	  .HasForeignKey(pg => new { pg.PlayerId, pg.CharacterId })
			//	  .HasPrincipalKey(ps => new { ps.PlayerId, ps.CharacterId });

			entity.OwnsOne(x => x.PlayerRating);
			// automatically exclude ignored players from all public queries
			entity.HasQueryFilter(ps =>
				!IgnoredPlayers.Any(ip => ip.PlayerId == ps.PlayerId));
		});

		modelBuilder.Entity<Game>(entity =>
		{
			entity.Property(g => g.ReplayId)
				.HasMaxLength(64)
				.IsRequired();

			entity.Property(g => g.PlayedAt)
				.HasConversion(
					v => ToStoredUtc(v),
					v => DateTime.SpecifyKind(v, DateTimeKind.Utc));

			entity.HasOne(g => g.CharacterA)
				.WithMany()
				.HasForeignKey(g => g.CharacterAId)
				.OnDelete(DeleteBehavior.Restrict);

			entity.HasOne(g => g.CharacterB)
				.WithMany()
				.HasForeignKey(g => g.CharacterBId)
				.OnDelete(DeleteBehavior.Restrict);
			// automatically exclude ignored players from all public queries			
			entity.HasQueryFilter(g =>
				!IgnoredPlayers.Any(ip => ip.PlayerId == g.PlayerAId) &&
				!IgnoredPlayers.Any(ip => ip.PlayerId == g.PlayerBId));
		});

		modelBuilder.Entity<Matchup>(entity =>
		{
			entity.HasKey(u => new { u.CharacterAId, u.CharacterBId });
			entity.ToTable(t =>
				t.HasCheckConstraint("CharacterOrder", "[CharacterAId] <= [CharacterBId]"));

			entity.HasOne(m => m.CharacterA)
				.WithMany()
				.HasForeignKey(m => m.CharacterAId)
				.OnDelete(DeleteBehavior.Restrict);

			entity.HasOne(m => m.CharacterB)
				.WithMany()
				.HasForeignKey(m => m.CharacterBId)
				.OnDelete(DeleteBehavior.Restrict);
		});

		modelBuilder.Entity<PlayerGame>(entity =>
		{
			entity.HasKey(u => new { u.PlayerId, u.GameId, u.CharacterId });

			entity.HasOne(p => p.Game)
				  .WithMany()
				  .HasForeignKey(p => p.GameId);

			entity.HasOne(p => p.Character)
				  .WithMany()
				  .HasForeignKey(p => p.CharacterId)
				  .OnDelete(DeleteBehavior.Restrict);

			entity.HasOne(x => x.Player)
				  .WithMany()
				  .HasForeignKey(x => x.PlayerId);

			entity.HasOne<PlayerCharacterStat>()
				  .WithMany(ps => ps.Games)
				  .HasForeignKey(pg => new { pg.PlayerId, pg.CharacterId })
				  .OnDelete(DeleteBehavior.Restrict);
			// automatically exclude ignored players from all public queries
			entity.HasQueryFilter(pg =>
				!IgnoredPlayers.Any(ip => ip.PlayerId == pg.PlayerId) &&
				!IgnoredPlayers.Any(ip => ip.PlayerId == pg.Game.PlayerAId) &&
				!IgnoredPlayers.Any(ip => ip.PlayerId == pg.Game.PlayerBId));
		});
	}

	private static DateTime ToStoredUtc(DateTime value)
	{
		if (value.Kind == DateTimeKind.Utc)
		{
			return value;
		}

		if (value.Kind == DateTimeKind.Local)
		{
			return value.ToUniversalTime();
		}

		return DateTime.SpecifyKind(value, DateTimeKind.Utc);
	}
}
