// <auto-generated />
using System;
using BBStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BBStats.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204221841_base")]
    partial class @base
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("BBStats.Data.Entites.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ragna"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Noel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rachel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Taokaka"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tager"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Litchi"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Arakune"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bang"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Carl"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Hakumen"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Nu"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Tsubaki"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Hazama"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Mu"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Makoto"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Valkenhayn"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Platinum"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Relius"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Izayoi"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Amane"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bullet"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Azrael"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Kagura"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Kokonoe"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Terumi"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Celica"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Lambda"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Hibiki"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Nine"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Naoto"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Izanami"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Susanoo"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Es"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Mai"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Jubei"
                        });
                });

            modelBuilder.Entity("BBStats.Data.Entites.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterBId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPlayerAWin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerA")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerAId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerB")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerBId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterAId");

                    b.HasIndex("CharacterBId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BBStats.Data.Entites.Matchup", b =>
                {
                    b.Property<int>("CharacterAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterBId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinsA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinsB")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterAId", "CharacterBId");

                    b.HasIndex("CharacterBId");

                    b.ToTable("Matchups", t =>
                        {
                            t.HasCheckConstraint("CharacterOrder", "\"CharacterAId\" < \"CharacterBId\"");
                        });
                });

            modelBuilder.Entity("BBStats.Data.Entites.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BBStats.Data.Entites.PlayerCharacterStat", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1000.0);

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("PlayersCharactersStats");
                });

            modelBuilder.Entity("BBStats.Data.Entites.PlayerGame", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EloAfter")
                        .HasColumnType("REAL");

                    b.Property<double>("EloBefore")
                        .HasColumnType("REAL");

                    b.Property<int?>("PlayerCharacterStatCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PlayerCharacterStatPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerCharacterStatPlayerId", "PlayerCharacterStatCharacterId");

                    b.ToTable("PlayersGames");
                });

            modelBuilder.Entity("BBStats.Data.Entites.Game", b =>
                {
                    b.HasOne("BBStats.Data.Entites.Character", "CharacterA")
                        .WithMany()
                        .HasForeignKey("CharacterAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BBStats.Data.Entites.Character", "CharacterB")
                        .WithMany()
                        .HasForeignKey("CharacterBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterA");

                    b.Navigation("CharacterB");
                });

            modelBuilder.Entity("BBStats.Data.Entites.Matchup", b =>
                {
                    b.HasOne("BBStats.Data.Entites.Character", "CharacterA")
                        .WithMany()
                        .HasForeignKey("CharacterAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BBStats.Data.Entites.Character", "CharacterB")
                        .WithMany()
                        .HasForeignKey("CharacterBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterA");

                    b.Navigation("CharacterB");
                });

            modelBuilder.Entity("BBStats.Data.Entites.PlayerCharacterStat", b =>
                {
                    b.HasOne("BBStats.Data.Entites.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BBStats.Data.Entites.Player", "Player")
                        .WithMany("CharactersStat")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BBStats.Data.Rating", "PlayerRating", b1 =>
                        {
                            b1.Property<long>("PlayerCharacterStatPlayerId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("PlayerCharacterStatCharacterId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("CurrentRating")
                                .HasColumnType("REAL");

                            b1.Property<double>("RatingDeviation")
                                .HasColumnType("REAL");

                            b1.Property<double>("Volatility")
                                .HasColumnType("REAL");

                            b1.HasKey("PlayerCharacterStatPlayerId", "PlayerCharacterStatCharacterId");

                            b1.ToTable("PlayersCharactersStats");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacterStatPlayerId", "PlayerCharacterStatCharacterId");
                        });

                    b.Navigation("Character");

                    b.Navigation("Player");

                    b.Navigation("PlayerRating")
                        .IsRequired();
                });

            modelBuilder.Entity("BBStats.Data.Entites.PlayerGame", b =>
                {
                    b.HasOne("BBStats.Data.Entites.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BBStats.Data.Entites.PlayerCharacterStat", null)
                        .WithMany("Games")
                        .HasForeignKey("PlayerCharacterStatPlayerId", "PlayerCharacterStatCharacterId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BBStats.Data.Entites.Player", b =>
                {
                    b.Navigation("CharactersStat");
                });

            modelBuilder.Entity("BBStats.Data.Entites.PlayerCharacterStat", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
