// <auto-generated />
using System;
using BBStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BBStats.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611213337_AddIgnoredPlayers")]
    partial class AddIgnoredPlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BBStats.Data.Entites.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ragna"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Noel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rachel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Taokaka"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tager"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Litchi"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Arakune"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bang"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Carl"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Hakumen"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Nu"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Tsubaki"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Hazama"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Mu"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Makoto"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Valkenhayn"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Platinum"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Relius"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Izayoi"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Amane"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bullet"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Azrael"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Kagura"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Kokonoe"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Terumi"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Celica"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Lambda"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Hibiki"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Nine"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Naoto"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Izanami"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Susanoo"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Es"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Mai"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Jubei"
                        });
                });

            modelBuilder.Entity("BBStats.Data.Entites.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterAId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterBId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlayerAWin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerA")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("PlayerAId")
                        .HasColumnType("bigint");

                    b.Property<string>("PlayerB")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("PlayerBId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReplayId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterAId");

                    b.HasIndex("CharacterBId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("BBStats.Data.Entites.IgnoredPlayer", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("PlayerId");

                    b.ToTable("IgnoredPlayers");
                });

            modelBuilder.Entity("BBStats.Data.Entites.Matchup", b =>
                {
                    b.Property<int>("CharacterAId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterBId")
                        .HasColumnType("int");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<int>("WinsA")
                        .HasColumnType("int");

                    b.Property<int>("WinsB")
                        .HasColumnType("int");

                    b.HasKey("CharacterAId", "CharacterBId");

                    b.HasIndex("CharacterBId");

                    b.ToTable("Matchups", t =>
                        {
                            t.HasCheckConstraint("CharacterOrder", "[CharacterAId] <= [CharacterBId]");
                        });
                });

            modelBuilder.Entity("BBStats.Data.Entites.Player", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BBStats.Data.Entites.PlayerCharacterStat", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<double>("MaxRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1000.0);

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("PlayerId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("PlayersCharactersStats");
                });

            modelBuilder.Entity("BBStats.Data.Entites.PlayerGame", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<double>("EloAfter")
                        .HasColumnType("float");

                    b.Property<double>("EloBefore")
                        .HasColumnType("float");

                    b.HasKey("PlayerId", "GameId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId", "CharacterId");

                    b.ToTable("PlayersGames");
                });

            modelBuilder.Entity("BBStats.Data.Entites.Game", b =>
                {
                    b.HasOne("BBStats.Data.Entites.Character", "CharacterA")
                        .WithMany()
                        .HasForeignKey("CharacterAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BBStats.Data.Entites.Character", "CharacterB")
                        .WithMany()
                        .HasForeignKey("CharacterBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CharacterA");

                    b.Navigation("CharacterB");
                });

            modelBuilder.Entity("BBStats.Data.Entites.Matchup", b =>
                {
                    b.HasOne("BBStats.Data.Entites.Character", "CharacterA")
                        .WithMany()
                        .HasForeignKey("CharacterAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BBStats.Data.Entites.Character", "CharacterB")
                        .WithMany()
                        .HasForeignKey("CharacterBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CharacterA");

                    b.Navigation("CharacterB");
                });

            modelBuilder.Entity("BBStats.Data.Entites.PlayerCharacterStat", b =>
                {
                    b.HasOne("BBStats.Data.Entites.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BBStats.Data.Entites.Player", "Player")
                        .WithMany("CharactersStat")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BBStats.Data.Rating", "PlayerRating", b1 =>
                        {
                            b1.Property<long>("PlayerCharacterStatPlayerId")
                                .HasColumnType("bigint");

                            b1.Property<int>("PlayerCharacterStatCharacterId")
                                .HasColumnType("int");

                            b1.Property<double>("CurrentRating")
                                .HasColumnType("float");

                            b1.Property<double>("RatingDeviation")
                                .HasColumnType("float");

                            b1.Property<double>("Volatility")
                                .HasColumnType("float");

                            b1.HasKey("PlayerCharacterStatPlayerId", "PlayerCharacterStatCharacterId");

                            b1.ToTable("PlayersCharactersStats");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacterStatPlayerId", "PlayerCharacterStatCharacterId");
                        });

                    b.Navigation("Character");

                    b.Navigation("Player");

                    b.Navigation("PlayerRating")
                        .IsRequired();
                });

            modelBuilder.Entity("BBStats.Data.Entites.PlayerGame", b =>
                {
                    b.HasOne("BBStats.Data.Entites.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BBStats.Data.Entites.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BBStats.Data.Entites.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BBStats.Data.Entites.PlayerCharacterStat", null)
                        .WithMany("Games")
                        .HasForeignKey("PlayerId", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BBStats.Data.Entites.Player", b =>
                {
                    b.Navigation("CharactersStat");
                });

            modelBuilder.Entity("BBStats.Data.Entites.PlayerCharacterStat", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
